### ISSUE TITLE
[Bug] On Windows, in TUN mode, UDP traffic via `socks5` outbound does not work properly.

### ISSUE THREAD

**Issue by toymil** [Dreamacro/clash#2853]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I am submitting an issue with the Clash core, not Clash.Meta / OpenClash / ClashX / Clash For Windows or any other derivative version
- [X] I am using the latest version of the Clash or Clash Premium core **in this repository**
- [X] I have searched at the [Issue Tracker](……/) **and have not found any related issues**
- [X] I have read the [official Wiki](https://dreamacro.github.io/clash/) **and was unable to solve the issue**
- [x] (required for Premium core) I've tried the `dev` branch and the issue still exists

### Version

Clash 2023.07.22 windows amd64 with go1.20.6 Sat Jul 22 09:44:10 UTC 2023

### Operating System

Windows

### Architecture

amd64

### Configuration File

```YAML
socks-port: 3000

allow-lan: false

mode: 'rule'

log-level: 'debug'

ipv6: true


interface-name: "wifi"

tun:
  enable: true
  stack: "gvisor"
  dns-hijack:
    - "198.18.0.2:53"
  auto-route: true
  auto-detect-interface: false


dns:
  enable: true
  ipv6: true
  listen: ':53'

  enhanced-mode: 'fake-ip'
  fake-ip-range: '198.18.0.1/16'
  fake-ip-filter:
    - '+.lan'
    - '+.localdomain'
    - '+.example'
    - '+.invalid'
    - '+.localhost'
    - '+.test'
    - '+.local'

  default-nameserver:
    - '223.5.5.5:53'
    - '223.6.6.6:53'
    - '[2400:3200::1]:53'
    - '[2400:3200:baba::1]:53'

  nameserver:
    - 'https://dns.alidns.com/dns-query'
    - 'https://223.5.5.5/dns-query'
    - 'https://223.6.6.6/dns-query'
    - 'https://[2400:3200::1]/dns-query'
    - 'https://[2400:3200:baba::1]/dns-query'


proxies:
  - name: "local xray"
    type: "socks5"
    server: "127.0.0.1"
    port: 2000
    udp: true

  - name: "router xray"
    type: "socks5"
    server: "192.168.1.1"
    port: 2222
    udp: true


proxy-groups:
  - name: 'Proxy'
    type: 'select'
    proxies:
      - "xray"
      - 'DIRECT'

  - name: 'Final'
    type: 'select'
    proxies:
      - 'DIRECT'
      - 'Proxy'
      - 'REJECT'

  - name: "xray"
    type: "select"
    proxies:
      - "local xray"
      - "router xray"


rules:
  - "PROCESS-NAME,curl.exe,xray"
  - "PROCESS-NAME,NatTypeTester-x64.exe,xray"

  - 'MATCH,Final'
```

### Log

```Text
Logs for multiple tests will be in the _Description_ section.
```

### Description

Setup:
- remote server at `example.com`
- host ip `192.168.1.153`
- xray on router, listen on `192.168.1.1:2222`  
  (if you are trying to reproduce the problem, _do not_ run xray on host.  clash outbound to another socks5 on the same machine has its own bugs, i might open an issue for that later)
- clash on host, listen on `127.0.0.1:3000`
- clash `PROCESS-NAME` rule for `curl.exe` and `NatTypeTester-x64.exe`, send to xray on router

Summary of 6 tests:  
TCP always work.  
`(udp) -> xray -> internet` (test 3) and  
`(udp) -> clash -> xray -> internet` (test 4) works,  
`(udp) -> tun -> clash -> xray -> internet` (test 6) doesn't.  
The xray side of log for UDP is essentially identical in all 3 UDP tests, so the problem seems to be introduced by clash's TUN implementation.

Tests:

1. no TUN, test if TCP via xray works
   `curl.exe -x socks5h://192.168.1.1:2222 https://google.com`
   flow: `(tcp) curl -> xray -> internet`
   result: 301 Moved
   <details><summary>xray log</summary>

   ```log
   2023/07/30 12:13:40 [Info] [1024857689] proxy/socks: TCP Connect request to tcp:google.com:443
   2023/07/30 12:13:40 [Info] [1024857689] app/dispatcher: taking detour [Remote] for [tcp:google.com:443]
   2023/07/30 12:13:40 [Info] [1024857689] transport/internet/grpc: creating connection to tcp:example.com:443
   2023/07/30 12:13:40 [Debug] transport/internet/grpc: using gRPC tun mode service name: `...` stream name: `Tun`
   2023/07/30 12:13:40 [Info] [1024857689] proxy/vless/outbound: tunneling request to tcp:google.com:443 via example.com:443
   2023/07/30 12:13:40 tcp:192.168.1.153:56105 accepted tcp:google.com:443 [SOCKS5 Inbound -> Remote]
   2023/07/30 12:13:42 [Info] [1024857689] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
   ```

   </details>

2. no TUN, test if TCP routed by clash to xray works
   `curl.exe -x socks5h://127.0.0.1:3000 https://google.com`
   flow: `(tcp) curl -> clash -> xray -> internet`
   result: 301 Moved
   <details><summary>xray log</summary>

   ```log
   2023/07/30 12:36:36 [Info] [370293662] proxy/socks: TCP Connect request to tcp:google.com:443
   2023/07/30 12:36:36 [Info] [370293662] app/dispatcher: taking detour [Remote] for [tcp:google.com:443]
   2023/07/30 12:36:36 [Info] [370293662] transport/internet/grpc: creating connection to tcp:example.com:443
   2023/07/30 12:36:36 tcp:192.168.1.153:50899 accepted tcp:google.com:443 [SOCKS5 Inbound -> Remote]
   2023/07/30 12:36:36 [Debug] transport/internet/grpc: using gRPC tun mode service name: `...` stream name: `Tun`
   2023/07/30 12:36:36 [Debug] transport/internet: dialing to tcp:example.com:443
   2023/07/30 12:36:37 [Info] [370293662] proxy/vless/outbound: tunneling request to tcp:google.com:443 via example.com:443
   2023/07/30 12:36:39 [Info] [370293662] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
   ```

   </details>
   <details><summary>clash log</summary>

   ```log
   20:36:36 DBG [TCP] accept connection lAddr=127.0.0.1:50898 rAddr=google.com:443 inbound=Socks5
   20:36:36 DBG [Matcher] find process success addr=google.com path=C:\Windows\System32\curl.exe
   20:36:36 INF [TCP] connected lAddr=127.0.0.1:50898 rAddr=google.com:443 mode=rule rule=Process(curl.exe) proxy=xray[router xray]
   ```

   </details>

3. no TUN, test if UDP via xray works
   NatTypeTester RFC3489 test with proxy set to `192.168.1.1:2222`
   flow: `(udp) NatTypeTester -> xray -> internet`
   result: FullCone
   <details><summary>xray log</summary>

   ```log
   2023/07/30 12:12:30 [Info] [2678885658] proxy/socks: client UDP connection from udp:192.168.1.153:57691
   2023/07/30 12:12:30 [Debug] [2678885658] proxy/socks: send packet to udp:139.59.84.212:3478 with 20 bytes
   2023/07/30 12:12:30 [Debug] [2678885658] transport/internet/udp: dispatch request to: udp:139.59.84.212:3478
   2023/07/30 12:12:30 [Info] transport/internet/udp: establishing new connection for udp:139.59.84.212:3478
   2023/07/30 12:12:30 [Info] [2678885658] app/dispatcher: taking detour [Remote] for [udp:139.59.84.212:3478]
   2023/07/30 12:12:30 [Info] [2678885658] transport/internet/grpc: creating connection to tcp:example.com:443
   2023/07/30 12:12:31 udp:192.168.1.153:57691 accepted udp:139.59.84.212:3478 [SOCKS5 Inbound -> Remote]
   2023/07/30 12:12:31 [Debug] transport/internet/grpc: using gRPC tun mode service name: `...` stream name: `Tun`
   2023/07/30 12:12:31 [Debug] transport/internet: dialing to tcp:example.com:443
   2023/07/30 12:12:32 [Info] [2678885658] proxy/vless/outbound: tunneling request to udp:139.59.84.212:3478 via example.com:443
   2023/07/30 12:12:33 [Debug] [2678885658] proxy/socks: writing back UDP response with 68 bytes
   2023/07/30 12:12:33 [Debug] [2678885658] proxy/socks: send packet to udp:139.59.84.212:3478 with 28 bytes
   2023/07/30 12:12:33 [Debug] [2678885658] transport/internet/udp: dispatch request to: udp:139.59.84.212:3478
   2023/07/30 12:12:33 [Debug] [2678885658] proxy/socks: writing back UDP response with 68 bytes
   ```

   </details>

4. no TUN, test if UDP routed by clash to xray works
   NatTypeTester RFC3489 test with proxy set to `127.0.0.1:3000`
   flow: `(udp) NatTypeTester -> clash -> xray -> internet`
   result: FullCone
   <details><summary>xray log</summary>

   ```log
   2023/07/30 12:37:29 [Info] [2082652799] proxy/socks: client UDP connection from udp:192.168.1.153:56718
   2023/07/30 12:37:29 [Debug] [2082652799] proxy/socks: send packet to udp:139.59.84.212:3478 with 20 bytes
   2023/07/30 12:37:29 [Debug] [2082652799] transport/internet/udp: dispatch request to: udp:139.59.84.212:3478
   2023/07/30 12:37:29 [Info] transport/internet/udp: establishing new connection for udp:139.59.84.212:3478
   2023/07/30 12:37:29 [Info] [2082652799] app/dispatcher: taking detour [Remote] for [udp:139.59.84.212:3478]
   2023/07/30 12:37:29 [Info] [2082652799] transport/internet/grpc: creating connection to tcp:example.com:443
   2023/07/30 12:37:29 [Debug] transport/internet/grpc: using gRPC tun mode service name: `...` stream name: `Tun`
   2023/07/30 12:37:29 [Info] [2082652799] proxy/vless/outbound: tunneling request to udp:139.59.84.212:3478 via example.com:443
   2023/07/30 12:37:29 udp:192.168.1.153:56718 accepted udp:139.59.84.212:3478 [SOCKS5 Inbound -> Remote]
   2023/07/30 12:37:29 [Debug] [2082652799] proxy/socks: writing back UDP response with 68 bytes
   2023/07/30 12:37:29 [Debug] [2082652799] proxy/socks: send packet to udp:139.59.84.212:3478 with 28 bytes
   2023/07/30 12:37:29 [Debug] [2082652799] transport/internet/udp: dispatch request to: udp:139.59.84.212:3478
   2023/07/30 12:37:29 [Debug] [2082652799] proxy/socks: writing back UDP response with 68 bytes
   ```

   </details>
   <details><summary>clash log</summary>

   ```log
   20:37:29 DBG [UDP] accept session lAddr=127.0.0.1:56717 rAddr=139.59.84.212:3478 inbound=Socks5
   20:37:29 DBG [Matcher] find process success addr=139.59.84.212 path=C:\NatTypeTester\NatTypeTester-x64.exe
   20:37:29 INF [UDP] connected lAddr=127.0.0.1:56717 rAddr=139.59.84.212:3478 mode=rule rule=Process(NatTypeTester-x64.exe) proxy=xray[router xray]
   ```

   </details>

5. with TUN, test if TCP captured by TUN, routed by clash, sent to xray still works
   `curl.exe https://google.com`
   flow: `(tcp) curl -> tun -> clash -> xray -> internet`
   result: 301 Moved
   <details><summary>xray log</summary>

   ```log
   2023/07/30 12:18:32 [Info] [3891344184] proxy/socks: TCP Connect request to tcp:google.com:443
   2023/07/30 12:18:32 [Info] [3891344184] app/dispatcher: taking detour [Remote] for [tcp:google.com:443]
   2023/07/30 12:18:32 [Info] [3891344184] transport/internet/grpc: creating connection to tcp:example.com:443
   2023/07/30 12:18:32 tcp:192.168.1.153:56427 accepted tcp:google.com:443 [SOCKS5 Inbound -> Remote]
   2023/07/30 12:18:32 [Debug] transport/internet/grpc: using gRPC tun mode service name: `...` stream name: `Tun`
   2023/07/30 12:18:32 [Debug] transport/internet: dialing to tcp:example.com:443
   2023/07/30 12:18:34 [Info] [3891344184] proxy/vless/outbound: tunneling request to tcp:google.com:443 via example.com:443
   2023/07/30 12:18:36 [Info] [3891344184] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
   ```

   </details>
   <details><summary>clash log</summary>

   ```log
   20:18:32 DBG [TUN] hijack udp dns addr=198.18.0.2:53
   20:18:32 DBG [TCP] accept connection lAddr=198.18.0.1:56426 rAddr=google.com:443 inbound=TUN
   20:18:32 DBG [Matcher] find process success addr=google.com path=C:\Windows\System32\curl.exe
   20:18:32 INF [TCP] connected lAddr=198.18.0.1:56426 rAddr=google.com:443 mode=rule rule=Process(curl.exe) proxy=xray[router xray]
   ```

   </details>

6. with TUN, test if UDP captured by TUN, routed by clash, sent to xray still works
   NatTypeTester RFC3489 test with no proxy set
   flow: `(udp) NatTypeTester -> tun -> clash -> xray -> internet`
   result: **_UnsupportedServer_**
   <details><summary>xray log</summary>

   ```log
   2023/07/30 12:19:24 [Info] [3278215638] proxy/socks: client UDP connection from udp:192.168.1.153:61836
   2023/07/30 12:19:24 [Debug] [3278215638] proxy/socks: send packet to udp:139.59.84.212:3478 with 20 bytes
   2023/07/30 12:19:24 [Debug] [3278215638] transport/internet/udp: dispatch request to: udp:139.59.84.212:3478
   2023/07/30 12:19:24 [Info] transport/internet/udp: establishing new connection for udp:139.59.84.212:3478
   2023/07/30 12:19:24 [Info] [3278215638] app/dispatcher: taking detour [Remote] for [udp:139.59.84.212:3478]
   2023/07/30 12:19:24 udp:192.168.1.153:61836 accepted udp:139.59.84.212:3478 [SOCKS5 Inbound -> Remote]
   2023/07/30 12:19:24 [Info] [3278215638] transport/internet/grpc: creating connection to tcp:example.com:443
   2023/07/30 12:19:24 [Debug] transport/internet/grpc: using gRPC tun mode service name: `...` stream name: `Tun`
   2023/07/30 12:19:24 [Info] [3278215638] proxy/vless/outbound: tunneling request to udp:139.59.84.212:3478 via example.com:443
   2023/07/30 12:19:24 [Debug] [3278215638] proxy/socks: writing back UDP response with 68 bytes
   2023/07/30 12:19:24 [Debug] [3278215638] proxy/socks: send packet to udp:139.59.84.212:3478 with 28 bytes
   2023/07/30 12:19:24 [Debug] [3278215638] transport/internet/udp: dispatch request to: udp:139.59.84.212:3478
   2023/07/30 12:19:25 [Debug] [3278215638] proxy/socks: writing back UDP response with 68 bytes
   ```

   </details>
   <details><summary>clash log</summary>

   ```log
   20:19:24 DBG [TUN] hijack udp dns addr=198.18.0.2:53
   20:19:24 DBG [DNS] dns response source=https://223.6.6.6/dns-query qType=A name=stun.syncthing.net. answer=["139.59.84.212","198.211.120.59"]
   20:19:24 DBG [DNS] dns response source=https://223.6.6.6/dns-query qType=AAAA name=stun.syncthing.net. answer=[]
   20:19:24 DBG [UDP] accept session lAddr=198.18.0.1:61835 rAddr=stun.syncthing.net:3478 inbound=TUN
   20:19:24 DBG [Matcher] find process success addr=stun.syncthing.net path=C:\NatTypeTester\NatTypeTester-x64.exe
   20:19:24 INF [UDP] connected lAddr=198.18.0.1:61835 rAddr=stun.syncthing.net:3478 mode=rule rule=Process(NatTypeTester-x64.exe) proxy=xray[router xray]
   ```

   </details>

### Reproduction Steps

See the _Description_ section and compare the results of test 4 and 6.

**Comment by toymil** [comment]
I don't have much networking knowledge, not sure if this is related to #2821.

**Comment by toymil** [comment]
this is a diagram from the [NatTypeTester](https://github.com/HMBSbige/NatTypeTester) project showing in which cases it will report `UnsupportedServer`:
![](https://github.com/HMBSbige/NatTypeTester/blob/75260f740a323045f8c179d972423a42a4cf07d7/pic/RFC3489.png)

**Comment by Dreamacro** [comment]
fixed #2821 , try premium latest

**Comment by toymil** [comment]
Emm, the latest premium release is still `2023.07.22`.

So I tried to compile the `dev` branch, but the resulting binary doesn't seems to create the tun device or changing the routing table at all?

What is the proper way to test this?

**Comment by toymil** [comment]
Oh, just saw the `latest` folder in S3 Storage, will try that now.

**Comment by toymil** [comment]
Ok, the behaviour is the same on `Clash 2023.07.22-16-gdcb610f windows amd64 with go1.21.0 Fri Aug 11 03:48:56 PM UTC 2023`, still shows _UnsupportedServer_.
